<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <groupId>iispl.com.demo</groupId>
  <artifactId>Checks</artifactId>
  <version>1.0.0</version>
  <packaging>war</packaging>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>

    <!-- ZK Core -->
    <dependency>
      <groupId>org.zkoss.zk</groupId>
      <artifactId>zk</artifactId>
      <version>10.0.0-jakarta</version>
    </dependency>

    <!-- ZK UI Components -->
    <dependency>
      <groupId>org.zkoss.zk</groupId>
      <artifactId>zul</artifactId>
      <version>10.0.0-jakarta</version>
    </dependency>

    <!-- ZK Binding -->
    <dependency>
      <groupId>org.zkoss.zk</groupId>
      <artifactId>zkbind</artifactId>
      <version>10.0.0-jakarta</version>
    </dependency>

  </dependencies>

  <build>
    <finalName>Checks</finalName>
  </build>

</project>